version: '3'
services:
  cromwell:
    image: "broadinstitute/cromwell:32"
    volumes:
      - ./cromwell-executions:/cromwell-working-dir/cromwell-executions
    command: ["/wait-for-it/wait-for-it.sh mysql-db:3306 -t 120 -- java -Dconfig.file=/app-config/application.conf -jar /app/cromwell.jar server"]
    links:
      - mysql-db
    ports:
      - "8000:80"
  mysql-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
