version: '3'
services:
  cromwell:
    image: "quay.io/comp-bio-aging/cromwell:master"
    volumes:
      - /data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/wait-for-it/wait-for-it.sh mysql-db:3306 -t 120 -- java -Dconfig.file=/data/sources/cromwell-client/services/cromwell/app-config/application.conf -jar /app/cromwell.jar server"]
    ports:
      - "8000:8000"
  mysql-db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /data/databases/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  cromwell-client:
    image: quay.io/comp-bio-aging/cromwell-web:0.2.3
    environment:
      - CROMWELL=http://cromwell:8000
      - CROMWELL_LOGS=/data/sources/cromwell-client/logs
    ports:
      - 8001:8001
    volumes:
         - /data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
