version: '3.8'
services:
  cromwell:
    image: "quay.io/comp-bio-aging/cromwell:latest"
    volumes:
      - /data:/data
      - /data/cromwell:/data/cromwell
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/wait-for-it/wait-for-it.sh mysql-db:3306 -t 120 -- java -Dconfig.file=/data/sources/cromwell-client/services/cromwell/application.conf -jar /app/cromwell.jar server"]
    ports:
      - "8000:8000"
  mysql-db:
    image: "mysql:8"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - /data/cromwell/mysql:/var/lib/mysql
      - /data/cromwell/mysql:/var/lib/mysql-files
    ports:
      - "3307:3306"
    cap_add:
      - ALL  # CAP_SYS_NICE
  cromwell-client:
    image: quay.io/comp-bio-aging/cromwell-web:latest
    environment:
      - CROMWELL=http://cromwell:8000
      - CROMWELL_LOGS=/data/sources/cromwell-client/logs
      - DATA=/data
    ports:
      - 8001:8001
    volumes:
      - /data:/data
      - /etc/hosts:/etc/hosts