version: '3'
services:
  cromwell:
    image: "quay.io/comp-bio-aging/cromwell:latest"
    volumes:
      - /pipelines:/pipelines
      - /pipelines/cromwell-executions:/cromwell-executions
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/wait-for-it/wait-for-it.sh mysql-db:3306 -t 120 -- java -Dconfig.file=/app-config/application.conf -jar /app/cromwell.jar server"]
    ports:h
      - "8000:8000"
  mysql-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=cromwell
      - MYSQL_DATABASE=cromwell_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /pipelines/data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  cromwell-client:
    image: quay.io/comp-bio-aging/cromwell-web:0.0.19
    ports:
      - 8001:8080
    volumes:
         - /pipelines:/pipelines
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
